import type { Program } from "@/lib/learning/types";

export const PROGRAM_MYSQL_LOGIN: Program = {
  id: "program-mysql-login",
  slug: "mysql-login",
  title: "MySQL Login",
  description: "Verify a user's credentials safely against a database.",
  category: "Databases",
  difficulty: "advanced",
  problemStatement:
    "Check a submitted username and password against a users table, hashing the password with password_verify() and preventing SQL injection with prepared statements.",
  concepts: ["Prepared statements", "password_verify()", "Sessions", "fetch_assoc()"],
  code: `<?php
session_start();

// Configuration placeholders — replace with your own server values.
$host     = "DB_HOST";
$username = "DB_USERNAME";
$password = "DB_PASSWORD";
$dbName   = "DB_NAME";

$conn = new mysqli($host, $username, $password, $dbName);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Simulated form input — in a real app this comes from $_POST.
$inputUser  = "Tabiq";
$inputPass  = "secret";

// ? is a placeholder; bind_param binds the concrete value safely.
$sql = "SELECT id, username, password_hash FROM users WHERE username = ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param("s", $inputUser);
$stmt->execute();

$result = $stmt->get_result();
if ($row = $result->fetch_assoc()) {
    if (password_verify($inputPass, $row["password_hash"])) {
        $_SESSION["user_id"] = $row["id"];
        echo "Login successful. Welcome, " . $row["username"] . "!";
    } else {
        echo "Invalid password.";
    }
} else {
    echo "User not found.";
}

$stmt->close();
$conn->close();`,
  expectedOutput: `Login successful. Welcome, Tabiq!`,
  explanation:
    "The query uses a placeholder (?) so user input is sent as data, never spliced into the SQL string — that blocks SQL injection. password_verify() compares the typed password against the stored hash generated by password_hash() at sign-up, without ever reconstructing the plaintext password. On success the user id is kept in the session so later requests know who is logged in.",
  notes: [
    "This script assumes a table 'users' with columns id, username, password_hash — no schema is invented here.",
    "Never compare passwords with ==; hashes make it impossible and password_verify() handles timing safety.",
    "DB_HOST, DB_USERNAME, DB_PASSWORD, DB_NAME are placeholders, not credentials.",
    "In production the session handling would live across separate pages, not inside the same script.",
  ],
};