import type { Program } from "@/lib/learning/types";

export const PROGRAM_MYSQL_CREATE_TABLE: Program = {
  id: "program-mysql-create-table",
  slug: "mysql-create-table",
  title: "Create & Drop a Table",
  description: "Create, recreate, inspect and drop a table with DDL.",
  category: "Databases",
  difficulty: "intermediate",
  problemStatement:
    "Drive the products table through its lifecycle — create it (idempotently), recreate it, report its state, and drop it — using raw DDL through the session's mysqli connection.",
  concepts: ["CREATE TABLE IF NOT EXISTS", "DROP TABLE IF EXISTS", "AUTO_INCREMENT PK", "DDL through mysqli"],
  code: `<?php
$config = require __DIR__ . "/academy_db_config.php";

$conn = mysqli_connect(
    $config["host"], $config["user"], $config["password"],
    $config["database"], $config["port"]
);
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}

// The physical table name is prefixed per session; the learner only ever
// thinks of "products".
$table = $config["table_prefix"] . "products";

$action = $_POST["action"] ?? "status";

if ($action === "create") {
    $sql = "CREATE TABLE IF NOT EXISTS \`$table\` (
        id    INT AUTO_INCREMENT PRIMARY KEY,
        name  VARCHAR(50)  NOT NULL,
        price DECIMAL(8,2) NOT NULL
    )";
    mysqli_query($conn, $sql);
    echo "Table created.";
} elseif ($action === "recreate") {
    mysqli_query($conn, "DROP TABLE IF EXISTS \`$table\`");
    $sql = "CREATE TABLE IF NOT EXISTS \`$table\` (
        id    INT AUTO_INCREMENT PRIMARY KEY,
        name  VARCHAR(50)  NOT NULL,
        price DECIMAL(8,2) NOT NULL
    )";
    mysqli_query($conn, $sql);
    echo "Table recreated.";
} elseif ($action === "drop") {
    mysqli_query($conn, "DROP TABLE IF EXISTS \`$table\`");
    echo "Table dropped.";
} else {
    $result = mysqli_query($conn, "SELECT COUNT(*) AS n FROM \`$table\`");
    $row = $result ? mysqli_fetch_assoc($result) : null;
    echo $row ? "Table has {$row["n"]} rows." : "0 rows.";
}

mysqli_close($conn);`,
  expectedOutput: "Table created.\nTable dropped.",
  explanation:
    "DDL runs through the same mysqli handle as any query. CREATE TABLE with IF NOT EXISTS makes creation idempotent: running it twice never errors. DROP TABLE cleans the table away, and its IF NOT EXISTS guard keeps dropping a missing table safe. SELECT COUNT(*) answers whether the table exists and how many rows it holds — the status action turns that into a readable line. Prefixing the physical name with the session's table prefix is essential: every session owns its own namespace inside the shared practice database.",
  notes: [
    "Always use IF NOT EXISTS / IF EXISTS for teachable idempotency; bare DDL raises errors on the second run.",
    "AUTO_INCREMENT PRIMARY KEY gives each row a stable identity without extra code.",
    "Backtick-quote the table name — the session prefix is generated by the server and is a safe identifier.",
  ],
  practice: {
    execution: "mysql",
    inputs: [
      {
        name: "action",
        label: "Action",
        type: "text",
        value: "create",
        description: "create, recreate, drop or status",
      },
    ],
    starterCode: `<?php

$conn = mysqli_connect(...);   // as in mysql-connect, from the injected
                               // academy_db_config.php (host, user, password,
                               // database, port)
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}

// Remember: the PHYSICAL table is $config["table_prefix"] . "products".
// Always create it with IF NOT EXISTS and drop it with IF EXISTS so a wrong
// sequence of actions never crashes the script.
//
//   action = create    -> CREATE TABLE IF NOT EXISTS products
//                          (id INT AUTO_INCREMENT PRIMARY KEY, name
//                           VARCHAR(50) NOT NULL, price DECIMAL(8,2) NOT NULL)
//                          then print "Table created."
//   action = recreate  -> DROP TABLE IF EXISTS, then create as above,
//                          print "Table recreated."
//   action = drop      -> DROP TABLE IF EXISTS, print "Table dropped."
//   action = status    -> SELECT COUNT(*) and print
//                          "Table has <n> rows." (or "0 rows." if unknown)

$action = $_POST["action"] ?? "status";

// Your logic here
`,
  },
  statefulTestCases: [
    {
      id: "create-creates-table",
      name: "Create makes the table",
      steps: [
        {
          inputs: { action: "create" },
          expectedOutput: "Table created.",
          expectedDb: [{ table: "products", rows: [] }],
        },
      ],
    },
    {
      id: "create-is-idempotent",
      name: "Create twice does not fail",
      steps: [
        {
          inputs: { action: "create" },
          expectedOutput: "Table created.",
          expectedDb: [{ table: "products", rows: [] }],
        },
        {
          inputs: { action: "create" },
          expectedOutput: "Table created.",
          expectedDb: [{ table: "products", rows: [] }],
        },
      ],
    },
    {
      id: "recreate-keeps-schema",
      name: "Recreate replaces the table",
      steps: [
        {
          inputs: { action: "create" },
          expectedOutput: "Table created.",
        },
        {
          inputs: { action: "recreate" },
          expectedOutput: "Table recreated.",
          expectedDb: [{ table: "products", rows: [] }],
        },
      ],
    },
    {
      id: "drop-removes-table",
      name: "Drop removes the table",
      steps: [
        {
          inputs: { action: "create" },
          expectedOutput: "Table created.",
        },
        {
          inputs: { action: "drop" },
          expectedOutput: "Table dropped.",
          expectedDb: [{ table: "products", rows: null }],
        },
      ],
    },
  ],
  hints: [
    {
      id: "conceptual",
      title: "Conceptual direction",
      content:
        "Tables are created and destroyed with DDL sent over the same connection handle as any query. The practice server names the physical table per session, so your code must prepend the config's table_prefix to the logical name \"products\".",
    },
    {
      id: "implementation",
      title: "Implementation approach",
      content:
        "Branch on the action field. The create branch issues CREATE TABLE IF NOT EXISTS and prints its confirmation; recreate drops first, then creates; drop just drops; status counts rows. Prefix every physical name with the config's table_prefix and backtick-quote it.",
    },
    {
      id: "step-level",
      title: "Step-by-step hint",
      content:
        "The grader runs several actions in one session, so plain CREATE TABLE without IF NOT EXISTS breaks the second create. After create the table must exist (empty); after drop it must be gone. If you forget the prefix, the grader's snapshot cannot find your table and the case reports missing DB state.",
    },
  ],
  lessonReferences: [{ lessonSlug: "mysql", label: "MySQL & Databases" }],
};